### ISSUE TITLE
Not able to connect or switch off the BBPOS x2

### ISSUE THREAD

**Issue by Bharanitharan06** [stripe/stripe-terminal-android#111]
Hi am new to stripe terminal integration. I developed android application for stripe terminal and connect the device for payment its works fine for me last one month but now am not able to connect device and not able to switch off manually. I don't know why its not turning off or connecting to mobile its continuously blinking with magenta and red

**Comment by aliriaz-stripe** [comment]
Hello @Bharanitharan06  , going to close this issue as Github Issues should be used for feature requests / bug reports for the Android Terminal SDK.

Could you write in with more details to Stripe Support (https://support.stripe.com/contact), details such as: 
- a video showing what happens when you power on the reader and the lights that flash
- are the readers discoverable when you call `discoverReaders()` in your application? 
- the result you get back when calling `connectReader()`, if any

Have you charged the reader recently? Try charging the reader for a couple of hours and try again.

Hope that helps!
