### ISSUE TITLE
Since `com.stripe:stripeterminal:2.1.0` not possible to overwrite `minSdkVersion`

### ISSUE THREAD

**Issue by jayjah** [stripe/stripe-terminal-android#157]
We are using version `com.stripe:stripeterminal:2.0.0-b3` and internally overwrite the minSdkVersion with the following, which is placed in AndroidManifest.xml

``` 
    <tools:overrideLibrary="com.stripe.Stripe, com.stripe.stripeterminal"/>
```

Since version 2.1.0 it's not possible to overwrite the minSdkVersion. 

Is this behaviour intended?
 If so, then please write it in your changelog. 
 If not, why it's not possible to overwrite minSdkVersion since version 2.1.0???

Actually it's for us NOT acceptable to bump the minSdkVersion just for the sake of the `stripeterminal` SDK.

**Comment by dhenry-stripe** [comment]
Hi @jayjah,

> Is this behaviour intended?

Yes, the behavior you're observing is intentional and was added in v2.0.0. The reason being that overriding `minSdkVersion` can lead to unexpected behavior in the Stripe SDK.

> Actually it's for us NOT acceptable to bump the minSdkVersion just for the sake of the stripeterminal SDK.

I understand your frustration and have updated the readme to explicitly call out the runtime API level validation. Please keep in mind though that Stripe Terminal Android has always required API 21, as listed [here](https://github.com/stripe/stripe-terminal-android#requirements).

**Comment by jayjah** [comment]
@dhenry-stripe Thank you very much for clarification, also thank you very much for mentioning in the README!
