### ISSUE TITLE
Handle transaction timeout

### ISSUE THREAD

**Issue by przemek9x9** [stripe/stripe-terminal-android#17]
I create payment intent on backend side and retrieve it on android side.
After a while (didn't measure it but it is ~30s) terminal timeout.
I can find on android console 

`2019-03-15 11:13:05.697 1793-1793/com.ourStripeTest D/Log: onReturnTransactionResult(TIMEOUT)`

How can we handle that scenario? I tried manually check payment status but it returns `REQUIRES_SOURCE ` even when is timeout.

**Comment by danwaters-stripe** [comment]
Hi,

Right now reader timeouts aren't being surfaced. I'll make sure to surface those (probably by throwing a TIMEOUT exception) in the next release so that you can retry the payment in that situation. For now, cancelling and restarting the payment will work if the reader gets stuck in that state. Thanks for the feedback!

**Comment by SharathKaribasappaGB** [comment]
HI, i have another scenario which yields the same error.
create a paymentIntent
collect paymentIntent
and then reader is waiting for card to be tapped/swiped
Now if do not swipe/tap the card for sometime in the console i see the logs
2019-04-04 14:41:50.204 2661-2661/com.genbook.android.manager.test D/Log: onReturnTransactionResult(TIMEOUT)
But the SDK does not return the same timeout info to the app, so app will not be aware of this and will be stuck there.

**Comment by danwaters-stripe** [comment]
This issue has been fixed in v1.0.0-b2 and will now throw a CARD_READ_TIMED_OUT exception.
