### ISSUE TITLE
Is there a command can make Android device make BBPOS terminal restart?

### ISSUE THREAD

**Issue by ohmyleonia** [stripe/stripe-terminal-android#177]
## Summary

We need a command can make android device restart BBPOS terminal.

Many of our BBPOS connect with kiosk, and sometime BBPOS got stock we will need to restart the kiosk or BBPOS to fix it. However, in most of cases kiosk is customer self facing only, and customer won't know how to fix such problem when it got stuck.

We will need a command can make our Android kiosk device ask BBPOS restart to avoid such problem, otherwise it will be unfriendly to our customers. It happened many times, and customers didn't know what's going on then canceled orders. We searched your documents and didn't find anything regarding this. Please provide us if it has, or please take this into your consideration for future SDK release.

Thanks.

## Android version
7 and 9

## Impacted devices (Android devices or readers)
BBPOS
## SDK version
2.4.0

**Comment by GODGINO** [comment]
+1

**Comment by dhenry-stripe** [comment]
Hi @ohmyleonia, we don't currently provide functionality to reset the connected BBPOS device using the Terminal SDK. It's possible though, we'll take it into consideration for future releases.

Can you share any more details about the BBPOS devices getting stuck? When a device gets stuck, are you able to connect to it via Bluetooth? If not, does the device still show up in Android Settings > Bluetooth?

**Comment by ohmyleonia** [comment]
Hello @dhenry-stripe , Thanks for taking it into your consideration, we are looking forward to.

It reproduced if cancel payment intent and remove/insert card happen at same time (in a second). But we tested again earlier today and it won't produce anymore, seems like it has been fixed after firmware updated? And it happened few times if BBPOS were used many times like more than 500 payments a day. 
We didn't notice about if the bluetooth were working, we just cannot send any command to BBPOS when it got stuck.

**Comment by GODGINO** [comment]
UNEXPECTED_ERROR.UNEXPECTED_SDK_ERRORCOMM_ERROR: Device no response (error code - 0055)

> Hi @ohmyleonia, we don't currently provide functionality to reset the connected BBPOS device using the Terminal SDK. It's possible though, we'll take it into consideration for future releases.
> 
> Can you share any more details about the BBPOS devices getting stuck? When a device gets stuck, are you able to connect to it via Bluetooth? If not, does the device still show up in Android Settings > Bluetooth?
UNEXPECTED_ERROR.UNEXPECTED_SDK_ERRORCOMM_ERROR: Device no response (error code - 0055)

**Comment by lidashancnjn** [comment]
> 
BBPOS often gets stuck and the error is UNEXPECTED_ERROR.UNEXPECTED_SDK_ERRORCOMM_ERROR: Device no response (error code-0055)
especially when it is connected via Bluetooth.
when error,It can be found in the search list of Bluetooth,  using Android's Bluetooth setting is also error.
I hope to provide a restart function that will allow BBPOS to connect after restarting

**Comment by lidashancnjn** [comment]
@dhenry-stripe View above

**Comment by jia748961024** [comment]
Why report this error and how to avoid error 0055？

**Comment by dhenry-stripe** [comment]
For any of the folks posting recently - do you have steps to reproduce and are you using the latest version (2.5.2)? If so, were you able to reproduce when using the example apps?

**Comment by MrDcm** [comment]
+1, I inserted a bank card, causing the card reader to jam and do no work. This situation is inevitable

**Comment by jia748961024** [comment]
> For any of the folks posting recently - do you have steps to reproduce and are you using the latest version (2.5.2)? If so, were you able to reproduce when using the example apps?

version(2.5.2) when Terminal.getInstance().retrievePaymentIntent or  Terminal.getInstance().collectPaymentMethod ,it happened.

**Comment by chr-stripe** [comment]
Hi folks, I know this ticket has been inactive for some time, so sorry for the long wait for a response.

We currently do not expose a command to restart the reader, though we'll take it into future consideration. While such a command may be a useful command in the general sense, using it as a means to resolve the reader being stuck may not be as helpful as we might imagine. For one, if the reader is stuck, frozen, or not responding, there's no guarantee that it will be able to receive and process a restart command in the first place!

@ohmyleonia your original issue may be resolved by the same fix for #194, so updating to version `2.13.0` (which will be available in the very near future) may resolve this for you.

As you might expect, we're committed to fixing bugs in the Terminal SDK, and would much prefer to solve the underlying issues at hand for everyone instead of exposing workarounds to be used individually. Using [our issue template](https://github.com/stripe/stripe-terminal-android/issues/new?assignees=&labels=&template=terminal-android-sdk-issue.md&title=) to file issues and providing details will always help us have more context around the issue. Providing additional logs or serial numbers for affected readers will also help tremendously!
