### ISSUE TITLE
must open GPS_PROVIDER ?

### ISSUE THREAD

**Issue by minjie0707** [stripe/stripe-terminal-android#189]
I have a device and only has the Network_provider , no GPS_PROVIDER  .   And Terminal.initTerminal failed . Is GPS_PROVIDER the    must need for the Terminal.initTerminal? 

version is 2.5.2

**Comment by dhenry-stripe** [comment]
Hi @minjie0707, `NETWORK_PROVIDER` should be all you need. Can you please post the error that you're seeing?

**Comment by minjie0707** [comment]
> Hi @minjie0707, `NETWORK_PROVIDER` should be all you need. Can you please post the error that you're seeing?

no error , just Terminal.initTerminal is failed .  Is this  means if the devices do not have the gps_provider  , they will can not use 
stripe-terminal-android sdk  ?

**Comment by minjie0707** [comment]
And I already granted this  Manifest.permission.ACCESS_FINE_LOCATION  permission , 

My device has no gps_provider  so this code  return false 

```
try {
            gpsEnabled = locationManager?.isProviderEnabled(LocationManager.GPS_PROVIDER) ?: false
        } catch (exception: Exception) {
        }
```

**Comment by minjie0707** [comment]
Is there a If statement in the sdk ?  Ff the gpsEnabled is false , it will make the Terminal.initTerminal  failed

**Comment by dhenry-stripe** [comment]
@minjie0707 this is what the SDK uses to validate location services: 
```
locationManager?.let {
  if (it.isProviderEnabled(LocationManager.GPS_PROVIDER) ||
      it.isProviderEnabled(LocationManager.NETWORK_PROVIDER)
  ) {
      return
  }
  throw TerminalException(
      TerminalException.TerminalErrorCode.LOCATION_SERVICES_DISABLED,
      "Location services must be enabled to use Terminal"
  )
```
So unless you're receiving a `TerminalException` with the message from the code snippet, the issue is likely something else.

Is there any more detail you can provide about `initTerminal` failing? How do you know it failed if you're not receiving an error?

**Comment by minjie0707** [comment]
> @minjie0707 this is what the SDK uses to validate location services:
> 
> ```
> locationManager?.let {
>   if (it.isProviderEnabled(LocationManager.GPS_PROVIDER) ||
>       it.isProviderEnabled(LocationManager.NETWORK_PROVIDER)
>   ) {
>       return
>   }
>   throw TerminalException(
>       TerminalException.TerminalErrorCode.LOCATION_SERVICES_DISABLED,
>       "Location services must be enabled to use Terminal"
>   )
> ```
> 
> So unless you're receiving a `TerminalException` with the message from the code snippet, the issue is likely something else.
> 
> Is there any more detail you can provide about `initTerminal` failing? How do you know it failed if you're not receiving an error?

thanks

**Comment by lambda0xff** [comment]
@dhenry-stripe : As it is currently, the code in the example application does not work with devices that do not have GPS because the the `verifyGpsEnabled` method will keep the app stuck with the permission dialog.

Just to be sure, can you confirm that the SDK does not require GPS and will work on devices that do not have GPS chips ?  If so, it might be usefull to change the example code or to mention it in the README ?
