### ISSUE TITLE
getBatteryLevel returns null for m2 reader

### ISSUE THREAD

**Issue by scottwilson312** [stripe/stripe-terminal-android#202]
## Summary
The battery level always reads as null for an M2 reader.

## Code to reproduce
Float battery = reader.getBatteryLevel();

This function always seems to return null. This is problematic for my use case because I have found that when the bluetooth m2 reader is on low battery, it will still allow connections however it will throw a very misleading "bluetooth disconnected unexpectedly" when trying to process a transaction.

 If I know the battery level I can programatically infer this scenario is occuring and can urge the app user to charge their M2 reader instead of leaving them confused thinking the reader is broken.

An alternative solution would be for the SDK to throw a "low battery" exception.

Thanks all for any help or advice. It is much appreciated.

**Comment by chenmin-stripe** [comment]
Hi @scottwilson312 

The `batteryLevel` you got from reader is the battery level when reader gets connected. It's not being updated since then. We have a coming release that will add `onBatteryLevelUpdate` callback in `ReaderListener` which you can use to monitor the battery level periodically (10mins). I hope this helps.
