### ISSUE TITLE
BBPOS no response when start retrievePaymentIntent

### ISSUE THREAD

**Issue by ohmyleonia** [stripe/stripe-terminal-android#216]
## Summary

While our client using BBPOS to make credit card payment, there were several BBPOS often got no response when we start the _Terminal.getInstance().retrievePaymentIntent(...)_. And they got stuck afterward. We found only if we turn off the BBPOS and wait for about 10 minutes to turn it on again can resolve this issue.  
Not sure why this happen or whether there are similar issue in git. Is it because long working duration of BBPOS?

## Code to reproduce

Terminal.getInstance().retrievePaymentIntent(...)

## Android version

Android 9
## Impacted devices (Android devices or readers)

BBPOS  example: CHB20Y118008596
## SDK version

2.6.0

**Comment by dhenry-stripe** [comment]
Hi @ohmyleonia,

> there were several BBPOS often got no response when we start the Terminal.getInstance().retrievePaymentIntent(...)

`retrievePaymentIntent` doesn't communicate with BBPOS. All this operation does is make a network call to the Stripe API. If this operation is the one that's getting stuck then the most likely explanation is that the network call is timing out due to poor connectivity. I don't see any errors on our side though, so it's possible that another operation is failing.

> And they got stuck afterward.

At what point does the transaction get stuck? I don't see any unexpected errors for `CHB20Y118008596` over the last 7 days.

**Comment by ohmyleonia** [comment]
Hello @dhenry-stripe 
> At what point does the transaction get stuck? I don't see any unexpected errors for `CHB20Y118008596` over the last 7 days.

It happened same that no response when start retrievePaymentIntent afterwards. But as you mentioned, if it is because of calling stripe API time  out. Then I guess following failure are the same reason.

We will try to optimize or change internet connection to resolve it at this point. If any further info we will let you know. Thank you.

**Comment by dhenry-stripe** [comment]
Sounds good, thanks for following up @ohmyleonia! Feel free to re-open if you discover that internet connectivity wasn't the cause.

**Comment by MrVipinVijayan** [comment]
retrievePaymentIntent just dont return anything on second call. no success, no failure callbacks. just get stuck on this call for ever.
