### ISSUE TITLE
`tipUnits` in metaData does not contain tipUnits

### ISSUE THREAD

**Issue by yogen-p** [stripe/stripe-terminal-android#228]
## Summary
The tipping value is not in the response of the `processPaymentCallback` for WisePad3. So, I need to store the original transactionAmount and then substract it from `paymentIntent.amount`. 

## Code to reproduce
Reproducible every time I make a payment with tip 
```Terminal.getInstance().processPayment(paymentIntent, processPaymentCallback)```

## Android version
12

## Impacted devices (Android devices or readers)
Doesn't matter

## SDK version
2.8.1

## Other information
This transaction had a transactionAmount of £10.00(1000 units) and a tip of £2.00(200 units)
<img width="626" alt="image" src="https://user-images.githubusercontent.com/56931531/164730215-d44021b2-1ec3-4906-95c9-b72bb7e17cff.png">

**Comment by sjl-stripe** [comment]
@yogen-p thanks for the report.  We're tracking this issue with our internal issue tracker and it will be addressed in a future release.

**Comment by yogen-p** [comment]
Hi @sjl-stripe This still seems to be broken on the latest SDK `2.17.0`


<img width="765" alt="image" src="https://user-images.githubusercontent.com/56931531/217292949-07307e10-c6af-4a5f-8648-74e6052eed29.png">

**Comment by billfinn-stripe** [comment]
@yogen-p -- can you clarify the problem you are seeing? The `amountTip` is available via `paymentIntent.amountDetails.tip.amount` in the `processPayment` callback.

Setting the on-reader tip amount in the metadata will not work because we only send the metadata to stripe.com when creating the payment intent. We are looking into supporting an `updatePaymentIntent` SDK method which would allow you to update the metadata after creating the PI.

**Comment by yogen-p** [comment]
Hi @billfinn-stripe , Thanks for clarifying that. The `amountTip` is available via `paymentIntent.amountDetails.tip.amount`.

I was looking in the wrong place. Apologies for the trouble
