### ISSUE TITLE
why the dialog popup ?

### ISSUE THREAD

**Issue by minjie0707** [stripe/stripe-terminal-android#238]
I am very curious about why this dialog popup in some android device and do not popup in other android device. 
Could you told me the reason?  Thanks so much .

<img width="695" alt="image" src="https://user-images.githubusercontent.com/82426849/173408352-3054c32e-e2e7-449c-b50b-b4a802169bd7.png">

stripe sdk: 2.9.0

**Comment by chr-stripe** [comment]
Hi @minjie0707, from what I can tell, this dialog popup is a feature of some Android hardware device manufacturers. Since the Stripe Terminal SDK reports that it recognizes readers when you plug them in, your Android device asks if you'd like to open your application using the SDK when the device is plugged in.

Is there a specific issue you're encountering with this dialog?

At this time, connecting to Stripe readers over USB remains in beta. You can read more about this USB connectivity methods [here](https://stripe.com/docs/terminal/payments/connect-reader?reader-type=usb). To request access, please contact us at [stripe-terminal-betas@stripe.com](mailto:stripe-terminal-betas@stripe.com).
