### ISSUE TITLE
Currency is unsupported or not set error on android phone with NFC 

### ISSUE THREAD

**Issue by ajithv11** [stripe/stripe-terminal-android#277]
Hi, 

I am getting the following error when I tried to collect NFC payment method from android phone (Samsung F23)
Stripe Terminal location is set as IE
`Error occured on : Terminal.getInstance().collectPaymentMethod`

Full code is given below

    val params = PaymentIntentParameters.Builder()
                                        .setAmount(100)
                                        .setCurrency("eur")
                                        .build()
        Terminal.getInstance().createPaymentIntent(params, object: PaymentIntentCallback {

            override fun onSuccess(paymentIntent: PaymentIntent) {

                val cancelable = Terminal.getInstance().collectPaymentMethod(paymentIntent,
                             object : PaymentIntentCallback {

                override fun onSuccess(paymentIntent: PaymentIntent) {

                }

                override fun onFailure(exception: TerminalException) {
                    Log.d("Custom Log","Collect PaymentMethod Error :> " + exception.message);
                    // Collect PaymentMethod Error :> Currency is unsupported or not set    This is the error I am getting
                }

            })
        }

        override fun onFailure(exception: TerminalException) {
            Log.d("Custom Log","Payment Intent Create Error : " + exception.errorMessage)
        }
    })

Error I am getting is Currency is unsupported or not set , It seems like currency is not set on mobile phone, I could not find the exact reason behind this issue

Thanks is advance

**Comment by chr-stripe** [comment]
The [Set up Tap on Mobile for Android](https://stripe.com/docs/terminal/payments/setup-reader/tap-on-mobile#getting-started) page details which countries Tap on Mobile is currently supported in:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/108023228/206123219-16db11d2-0113-4adf-aea1-687a61f49e66.png">

These countries are
- Australia
- Canada
- New Zealand
- Singapore
- United States of America

None of these countries use the euro as their national currency, which is why `"eur"` is coming up as an unsupported currency when you attempt to collect it using Tap on Mobile.

This may change in the future as we explore expanding this feature globally.

**Comment by ajithv11** [comment]
@chr-stripe  But it works when I use GBP as currency and address location as UK  and stripe was on test mode on both cases

**Comment by chr-stripe** [comment]
It does look like Tap to Pay on Android is enabled in `GB` if you are included in the private beta.

However, `IE` (Ireland) is a separate country from `GB` (the United Kingdom of Great Britain and North Ireland), and Tap to Pay on Android will not work if your account is registered in Ireland at all. I also don't believe we support processing `GBP` from an `IE` account.

You will need to use an account registered in one of the countries I specified above (or Great Britain if included in the private beta), **and** be processing that country's local currency in order to use Tap to Pay on Android.
