### ISSUE TITLE
how to properly cancel payment

### ISSUE THREAD

**Issue by jianming** [stripe/stripe-terminal-android#282]
## Summary
When a user cancels the payment, then tries again, the reader will behave very weirdly: the SDK will not emit "insert/tap" message, when the user taps the reader, it beeps and show remove card or something retry card, then it will emit "Insert/Tap" message, user has to try again to pay again. It gives the impression that multiple charges. 

But if the user pays directly without cancellation first, the insert/tap messages show instantly and everything works.

Also if we cancel one payment, then try another payment even with a fresh session, it will behave the same until a successful payment happens, then everything is back to normal.

So our question is: what is the correct logic to handle payment cancelation, and is there any way to reset the reader so it will have a clean start??

here is the video

https://user-images.githubusercontent.com/238326/208356307-5dbd0a47-d2dd-4d49-8868-218ea2b8b797.MOV

## Code to reproduce
In our code, when the user click cancels the payment, we will cancel the payment intent. And when the user clicks pay again, our logic will generate a new payment intent and everything is new. But somehow the reader is stuck in some old state and shows some weird behavior. 

## Android version
11-13

## SDK version
2.16

## Other information
Please help us to provide the best way to handle the cancellation. The issue does not happen with simulated reader, but it happens with the real M2 readers.

**Comment by chr-stripe** [comment]
Hi @jianming, can you comment on what method you're using to cancel the payment intent? Or more directly, what happens when you are clicking on the `✖️` in the top-left? From the video you had posted (which is very helpful to describe what's happening – thank you!), it looks like the first LED on the M2 reader stays lit after you start the first payment intent, even after it's canceled:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/108023228/208756142-45001a1c-ce47-4455-ae2e-4c4494e35bf7.png">

Our [product spec sheet](https://d37ugbyn3rpeym.cloudfront.net/terminal/product-sheets/m2_product_sheet.pdf) (which can be found on our [M2 product page](https://stripe.com/docs/terminal/readers/stripe-m2)) notes that a single LED lit up means the reader is ready for a payment method to be presented. My suspicion is that the payment intent is not being properly canceled through the SDK, leading to some kind of issue when you attempt the second payment intent request. Can you post a code snippet of roughly how you're performing that cancellation?

**Comment by jianming** [comment]
We retrieve the payment intent, then call this method: cancelPaymentIntent

But it seems after calling this method, the reader is still pending for card, so I have to tap the card, then it will show remove card, then the previous payment intent seems really cancellation, then it will show insert/tap again.

So our questions is how we can properly reset the payment process (cancelation) so it will have a clean start just like a new payment process.

**Comment by jianming** [comment]
We create the paymentIntent from our backend, then the client fetch the ID, then call retreivePaymentIntent via your SDK, then we call the cancelPaymentIntent in the SDK when user click X icon and confirm the cancelation

**Comment by chr-stripe** [comment]
This looks very similar to the recently-reported #285, especially looking at the videos posted. Based on the description you provided, I believe it should be resolved by the same change mentioned [here](https://github.com/stripe/stripe-terminal-android/issues/285#issuecomment-1370062583):

> [...] to cancel a payment in the event that the user has changed their mind, please use the `Cancelable` returned from `collectPaymentMethod`. Calling `Cancelable.cancel` will issue a command to the reader which will cancel the payment method collection process.
> 
> Then, if you would also like to cancel the Payment Intent in the backend, you may also call `Terminal.cancelPaymentIntent`.

**Comment by jianming** [comment]
Thanks. It fixes the issue.
