### ISSUE TITLE
User-Initiated Tap to Pay Reader disconnect triggers 'onUnexpectedReaderDisconnect' event

### ISSUE THREAD

**Issue by choang10** [stripe/stripe-terminal-android#306]
## Summary

After successfully connecting to a local mobile reader, calling Terminal.getInstance().disconnectReader() triggers the 'onUnexpectedReaderDisconnect' event, causing the TerminalListener method to be called. I've tested on the same physical device using the simulated BT card reader, and calling the disconnectReader() method doesn't trigger that event (it does still trigger the 'onConnectionStatusChange' and 'onPaymentStatusChange' events).

## Android version

13

## Impacted devices (Android devices or readers)

Google Pixel 4A

## SDK version

implementation "com.stripe:stripeterminal-localmobile:2.18.0-b0"
implementation "com.stripe:stripeterminal-core:2.18.1"

## Other information

It might be worth noting that this project is built using Nativescript with generated TS typings, though it hasn't impacted any other areas of our SDK implementation.

**Comment by jronnen7** [comment]
I am having this issue too.  It only happens when we disconnect from COTS device on android.

## Android version
13

## Impacted devices (Android devices or readers)
Google Pixel 7

## SDK version
implementation "com.stripe:stripeterminal-localmobile:2.20.1"
implementation "com.stripe:stripeterminal-core:2.20.1"

## Other Information
IOS terminal sdk doesn't throw the unexpected disconnect event

**Comment by maggiewhite-stripe** [comment]
@choang10 This issue was fixed in the 2.21.1 release - please re-open this ticket if you still see this problem in the 2.21.1 release or newer.
