### ISSUE TITLE
Getting null in connectedReader.getBatteryLevel() after updating to 2.19.0

### ISSUE THREAD

**Issue by arbaz8dots** [stripe/stripe-terminal-android#310]
## Summary
Getting null in connectedReader.getBatteryLevel() after updating to 2.19.0

## Code to reproduce
 txt_battery_level.setText("Battery Level:- " + (connectedReader.getBatteryLevel() * 100f) + "%");

## Android version
 Android 13

## Impacted devices (Android devices or readers)
 BBPOS3

## SDK version
com.stripe:stripeterminal:2.19.0

## Other information
 Getting null only after updating to 2.19.0, In 2.18.1 and below it's working

**Comment by chr-stripe** [comment]
Yep, I'm able to reproduce this. Seems like we're not getting the battery info at the point of connecting to it. Will need to dig into this further as to why this is happening in 2.19.0.

That being said, in your [`ReaderListener`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-reader-listener/index.html) implementation, you should still be getting a [`onBatteryLevelUpdate()`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-reader-listener/on-battery-level-update.html) callback shortly after connecting to the reader as well as every 10 minutes while you're still connected to it. This value will always be the most accurate and up-to-date measure of the current battery level in your reader.

**Comment by chr-stripe** [comment]
Thank you for the bug report! This will be fixed in Terminal Android SDK `2.21.0`: the `connectedReader` will contain the battery info immediately upon connection. However as with before, listening to the [`onBatteryLevelUpdate()`](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-reader-listener/on-battery-level-update.html) callbacks will always be the preferred method to get more accurate battery level updates for the duration of your connection to the reader.

I can leave this issue open until that version is released and give you a reminder when it's available, if you like.

**Comment by chr-stripe** [comment]
Terminal SDK `2.21.0` has been released, which resolves this issue.
