### ISSUE TITLE
TerminalException: User canceled the transaction

### ISSUE THREAD

**Issue by guolijun** [stripe/stripe-terminal-android#320]
com.stripe.stripeterminal.external.models.TerminalException: User canceled the transaction.

## Summary
createPaymentIntent CaptureMethod is Automatic
OK if try createPaymentIntent again.

## Android version
11,12

## Impacted devices (Android devices or readers)
Stripe M2

## SDK version
2.20.0

**Comment by majjinator** [comment]
I am also encountering this issue after upgrading from 2.19.0 to 2.20.0. The behavior is that a first payment using the Reader M2 completes successfully, but the next payment always fails with the exception shown below. The next attempt after the failure then proceeds successfully, and the cycle repeats, with payment following a successful payment always failing.

Upon reverting back to 2.19.0, the issue no longer occurs, however, according to a recent Stripe communication, the 2.20.0 build will be required for Tap to Pay after July 15.  Also confirmed that the issue is present in the 2.20.1 version.

I should note that the exception that is occurring is the same type that is triggered if you explicitly cancel the Cancelable task that is created using Terminal.getInstance().collectPaymentMethod(). So it appears that there was a change in 2.20.0 that is automatically triggering cancelation of the collectPayment task, for every other payment attempt.

The changelog for 2.20.0 mentions "Fix: Errors from canceling and creating PaymentIntents and SetupIntents no longer return a generic "Unexpected null" message on internet readers." I'm guessing this fix introduced the regression.

### Log Output

D/StripeTerminal(17042): class=Terminal message=createPaymentIntent
D/StripeTerminal(17042): class=OnlineDirectResourceRepository message=createPaymentIntent
D/StripeTerminal(17042): class=ApiClient message=createPaymentIntent
I/StripeTerminal(17042): class=RestClient message="url=https://api.stripe.com/v1/payment_intents request={"amount":"11497","captureMethod":"manual","currency":"usd","paymentMethodOptions":{"cardPresent":{}},"paymentMethodTypes":["card_present"]}"
I/RestResponse(17042): REST response with code 200 received
I/RestResponse(17042): request-id: req_xxxx
I/StripeTerminal(17042): class=RestClient message="url=https://api.stripe.com/v1/payment_intents status=OK headers={access-control-allow-credentials=true, access-control-allow-methods=GET, POST, HEAD, OPTIONS, DELETE, access-control-allow-origin=*, access-control-expose-headers=Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required, access-control-max-age=300, cache-control=no-cache, no-store, content-length=1472, content-type=application/json, date=Wed, 17 May 2023 19:38:42 GMT, idempotency-key=xxxx, original-request=xxx, request-id=xxx, server=nginx, strict-transport-security=max-age=xx; includeSubDomains; preload, stripe-account=xxx, stripe-should-retry=false, stripe-version=2019-02-19, x-stripe-routing-context-priority-tier=api-testmode} response={"amount":"11497","amountCapturable":"0","amountDetails":{"tip":{}},"amountReceived":"0","captureMethod":"manual","charges":{"hasMore":false,"totalCount":0},"clientSecret":"xxx","created":"xxx","currency":"usd","id":"xxx","livemode":false,"paymentMethodOptions":{"cardPresent":{}},"status":"requires_payment_method"}"
D/StripeTerminal(17042): class=Terminal message=collectPaymentMethod
I/StripeTerminal(17042): class=TerminalStatusManager message=waitForInput.
D/StripeTerminal(17042): class=ProxyTerminalListener message=onPaymentStatusChange(WAITING_FOR_INPUT)
D/StripeTerminal(17042): class=BbposBluetoothAdapter message=collectPaymentMethod amount="Amount(value=11497, currency=USD)" type=com.stripe.jvmcore.transaction.PaymentMethodCollectionType$Sale@ad2d2b7
I/StripeTerminal(17042): class=PaymentCollectionCoordinatorWrapper message="Updating devicePaymentCapability to PaymentCollectionDeviceCapability(directlyControlsScreenInput=false, supportExtendedTransaction=false, checkForCardBehavior=DO_NOT_POLL, supportedInterface=[MAGSTRIPE, ICC, NFC], retryUponPinCancel=false, quickEmvAutoResponse=true)"
I/StripeTerminal(17042): class=DiscreteEventLogger message="logOnlineConfirmResult result FAILURE failureReason MERCHANT_CANCELLED"
I/StripeTerminal(17042): class=PaymentCollectionStateMachine message="onStateChanged: ONLINE_CONFIRMATION -> CANCEL: MERCHANT_CANCELLED"
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent StopReaderEvent(phase=COLLECTION)"
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent com.stripe.core.paymentcollection.CollectionCancelledEvent@7cc5840"
I/StripeTerminal(17042): class=PaymentCollectionStateMachine message="onStateChanged: CANCEL -> FINISHED: Transaction cancelled."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Payment collection metric ending in 40548 ms: result FAILURE, tagMap {PaymentMethodType=EMV_TAP, TransactionType=CHARGE, EmvTransactionType=QUICK, ApplicationId=VISA_CREDIT, CollectionFailureReason=MERCHANT_CANCELLED, stateWhenCancelled=ONLINE_CONFIRMATION}"
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category USER_ACTION took 0 ms."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category KERNEL_PROCESSING took 7158 ms."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category POS_COMMAND_DELAY took 541 ms."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category NETWORK_PROCESSING took 1070 ms."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category UNKNOWN took 32597 ms."
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent CollectionCompleteEvent(model=CollectionCompletedModel(result=CANCELLED, amount=Amount(value=52323, currency=USD)))"
I/StripeTerminal(17042): class=StageEventLogger message="KernelProcessing newStatus BUSY event StopReaderEvent"
I/StripeTerminal(17042): class=StageEventLogger message="Starting event KernelProcessing with latencyCategory KERNEL_PROCESSING"
D/StripeTerminal(17042): class=BbposDeviceControllerImpl message=cancelCheckCard
D/StripeTerminal(17042): class=BbposAdapterPaymentCollectionListener message=onCancelled
D/StripeTerminal(17042): class=BbposAdapterPaymentCollectionListener message="onCollectionComplete CollectionCompletedModel(result=CANCELLED, amount=Amount(value=52323, currency=USD))"
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="Not starting the tipping flow because there is no tipping config"
I/StripeTerminal(17042): class=PaymentCollectionStateMachine message="onStateChanged: null -> EMPTY: null"
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent CardStateUpdateEvent(cardState=EMPTY)"
I/StripeTerminal(17042): class=PaymentCollectionStateMachine message="onStateChanged: EMPTY -> COLLECTION: Tipping and manual entry not required."
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent ConfigureReaderEvent(configuration=ReaderConfiguration(readersEnabled=[MAGSTRIPE, ICC, NFC], transactionAmount=Amount(value=11497, currency=USD), transactionType=GOODS, emvTransactionType=QUICK, quickChipMode=USE_CONFIG, terminalCapabilitiesOverride=null, domesticDebitPriority=null, contactlessOnlinePinOption=null))"
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent PresentPaymentMethodEvent(model=CollectionModel(transactionType=CHARGE, amount=Amount(value=11497, currency=USD), baseAmount=Amount(value=11497, currency=USD), callToAction=null, readerActiveInterfaces=[MAGSTRIPE, ICC, NFC], readerContactCardSlotState=EMPTY, readerEnableEditTip=false))"
D/StripeTerminal(17042): class=BbposAdapterPaymentCollectionListener message="onCardStateUpdate EMPTY"
I/StripeTerminal(17042): class=StageEventLogger message="KernelProcessing newStatus BUSY event ConfigureReaderEvent"
D/StripeTerminal(17042): class=BbposDeviceControllerImpl message=startEmv
D/StripeTerminal(17042): class=BbposAdapterPaymentCollectionListener message=onRequestPaymentMethodCollection
I/StripeTerminal(17042): class=TerminalStatusManager message="requestReaderInput Swipe / Insert / Tap."
I/StripeTerminal(17042): class=ProxyReaderListener message="onRequestReaderInput(Swipe / Insert / Tap)"
I/StripeTerminal(17042): class=BbposPaymentCollectionListener message=onReturnCancelCheckCardResult
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent com.stripe.core.paymentcollection.HardwareTransactionCancelledEvent@c42c8be"
I/StripeTerminal(17042): class=StageEventLogger message="KernelProcessing newStatus IDLE event HardwareTransactionCancelledEvent"
I/StripeTerminal(17042): class=StageEventLogger message="Reporting KernelProcessing outcome com.stripe.jvmcore.loggingmodels.Outcome$Ok@78349c2 tags {PaymentMethodType=UNKNOWN, TransactionType=CHARGE, KernelProcessingResult=HardwareTransactionCancelledEvent, EmvTransactionType=QUICK, LatencyCategory=KERNEL_PROCESSING}"
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent com.stripe.core.paymentcollection.ClearMagStripeStateEvent@4bbc609"
I/StripeTerminal(17042): class=PaymentCollectionStateMachine message="onStateChanged: COLLECTION -> CANCEL: HARDWARE_CANCELLED"
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent com.stripe.core.paymentcollection.CollectionCancelledEvent@7cc5840"
I/StripeTerminal(17042): class=PaymentCollectionStateMachine message="onStateChanged: CANCEL -> FINISHED: Transaction cancelled."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Payment collection metric ending in 61 ms: result FAILURE, tagMap {PaymentMethodType=UNKNOWN, TransactionType=CHARGE, EmvTransactionType=QUICK, CollectionFailureReason=MERCHANT_CANCELLED, stateWhenCancelled=COLLECTION}"
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category USER_ACTION took 0 ms."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category KERNEL_PROCESSING took 0 ms."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category POS_COMMAND_DELAY took 0 ms."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category NETWORK_PROCESSING took 0 ms."
I/StripeTerminal(17042): class=EndToEndEventLogger message="Category UNKNOWN took 79 ms."
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent CollectionCompleteEvent(model=CollectionCompletedModel(result=CANCELLED, amount=Amount(value=11497, currency=USD)))"
D/StripeTerminal(17042): class=BbposAdapterPaymentCollectionListener message=onCancelled
D/StripeTerminal(17042): class=BbposAdapterPaymentCollectionListener message="onCollectionComplete CollectionCompletedModel(result=CANCELLED, amount=Amount(value=11497, currency=USD))"
I/StripeTerminal(17042): class=TerminalStatusManager message=endPaymentFlow.
D/StripeTerminal(17042): class=ProxyTerminalListener message=onPaymentStatusChange(READY)
E/StripeTerminal(17042): class=TerminalSession
E/StripeTerminal(17042): com.stripe.stripeterminal.external.models.TerminalException: User canceled the transaction.
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.adapter.PaymentCollectionCoordinatorWrapper.collectPaymentMethodHelper(PaymentCollectionCoordinatorWrapper.kt:266)
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.adapter.PaymentCollectionCoordinatorWrapper.collectPaymentMethod(PaymentCollectionCoordinatorWrapper.kt:134)
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter.collectPaymentMethod(BbposAdapter.kt:224)
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.collectPaymentMethod(ProxyAdapter.kt:147)
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CollectPaymentMethodOperation.executeIfNotCanceled(TerminalSession.kt:1172)
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CancelableOperation.execute(TerminalSession.kt:947)
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:905)
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$3(TerminalSession.kt:765)
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$l3D1f-Vk5Q8NcJKxkmByt8wMjwc(Unknown Source:0)
E/StripeTerminal(17042): 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StripeTerminal(17042): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
E/StripeTerminal(17042): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/StripeTerminal(17042): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/StripeTerminal(17042): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/StripeTerminal(17042): 	at java.lang.Thread.run(Thread.java:764)
I/StripeTerminal(17042): class=BbposPaymentCollectionListener message="onRequestDisplayText PRESENT_CARD"
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent com.stripe.core.paymentcollection.WaitForCardPresentEvent@12ad60d"
I/StripeTerminal(17042): class=BbposPaymentCollectionListener message="onWaitingForCard SWIPE_OR_INSERT_OR_TAP"
I/StripeTerminal(17042): class=PaymentCollectionCoordinator message="onHandlePaymentCollectionEvent ReaderTypeChangedEvent(types=[MAGSTRIPE, ICC, NFC])"

**Comment by rv-stripe** [comment]
Looking into this issue, but have been unable to reproduce it. Are you able to reproduce this using the example integration?

**Comment by guolijun** [comment]
collectTask?.cancel in collectPaymentMethodCallback onSuccess, the issue does not occur.
```kotlin
// Step 3 - we've collected the payment method, so it's time to process the payment
        val collectPaymentMethodCallback = object : PaymentIntentCallback {
            override fun onSuccess(paymentIntent: PaymentIntent) {
                Terminal.getInstance().processPayment(paymentIntent, processPaymentCallback)
                collectTask?.cancel(object : Callback {
                    override fun onFailure(e: TerminalException) {
                    }

                    override fun onSuccess() {
                    }

                })
            }

            override fun onFailure(e: TerminalException) {
                // Update UI w/ failure
            }
        }
```

**Comment by rv-stripe** [comment]
Does the issue happen consistently or intermittently?
Could you also provide the options you're using for `collectConfig` -- that may help us track down what's causing this.

**Comment by guolijun** [comment]
the issue happen as [majjinator](/majjinator) description

collectConfig irrelevant

**Comment by majjinator** [comment]
The issue happens consistently i.e. every second attempt to collect payment will always fail. I have also confirmed that this happens with all Bluetooth readers (Reader M2, Chipper 2X and WisePad3). We use server integration for the WisePOS-E, so the issue does not arise there, and neither does it affect Tap to Pay.

As @guolijun mentioned, the issue still occurs regardless of whether collectConfig is specified or not i.e. both:

`collectTask = Terminal.getInstance().collectPaymentMethod( paymentIntent, collectPaymentMethodCallback, collectConfig);`

and 

`collectTask = Terminal.getInstance().collectPaymentMethod( paymentIntent, collectPaymentMethodCallback);`

will trigger the issue.

The culprit might lie in what @guolijun mentioned above, with regard to canceling the collectTask after the payment details are captured in the first transaction. As shown in the example application, after the payment details are captured, the collectTask is disposed by setting it to null:

`collectTask = null; `

This works fine up until 2.19.0. With 2.20.0 and 2.20.1, the issue will manifest unless the collectTask is explicitly canceled after payment details are captured i.e. you have to do:

           collectTask.cancel(new Callback() {
                @Override
                public void onSuccess() {
                   //
                }

                @Override
                public void onFailure(@NonNull TerminalException e) {
                   //
                }
            });
            collectTask = null;

If the collectTask is canceled, then the subsequent transaction will not fail. It therefore seems that there was a change introduced in 2.20.0 that is causing the collectTask to persist within the Stripe SDK, even after it has been set to null in the client code, thus causing subsequent transactions to encounter the phantom collectTask and fail.

**Comment by rv-stripe** [comment]
I'm trying to identify what could be causing that behavior difference between the example app and your integration.
Setting the reference to `null` in the integration will have no effect on the SDK. But you should not need to cancel it either unless you want to stop the transaction.
Could you share the ID of a reader that you have seen the issue on recently? That will help me look up logs on our end.

**Comment by majjinator** [comment]
Here is a Reader M2 in test mode: tmr_FGNwFwssyGVh4G

A request that is successful:  req_4fJrL64wdzX4bC

Subsequent one that fails: req_RmNvTkduDsmBw2

BTW, is androidx.lifecycle:lifecycle-viewmodel-ktx used in the SDK, and if so, which version?

**Comment by bperez-stripe** [comment]
@guolijun @majjinator is this issue still occurring? We have made some updates to the SDK. Can you try reproducing on the latest SDK and provide updated PIs or Request IDs to continue the investigation?

**Comment by guolijun** [comment]
only occurred in version 2.20.0

**Comment by bperez-stripe** [comment]
Great. Happy to hear the issue is not seen on newer SDK versions.
