### ISSUE TITLE
Tap to Pay stuck at scan page screen

### ISSUE THREAD

**Issue by xez4** [stripe/stripe-terminal-android#339]
## Summary
We received several reports from users that TTP is not responding to the card, beep sound and nothing was happening, looks like a problem with your server, in the logs we got this - com.stripe.stripeterminal.external.models.TerminalException: API_CONNECTION_ERROR (null). Then this report from our backend developer - "The interesting case got tonight -
I needed to test the TTP (backend update), but both apps opened the TTP Scan page without allowing me to read the card. I tried restarting and reloading, but nothing helped...
Just nothing - no errors no responses. After sometime showed me timeout.
Today morning - all is good"
This was happening on different days, an important point is that it affected both platforms android & ios which again hints at server problems... We hope for your help!
## SDK version
2.20.1

**Comment by maggiewhite-stripe** [comment]
Hey @xez4, the implementations for android and iOS are very different so it's incredibly unlikely that the cause of the issue is the same on both platforms.

Please file a ticket on the iOS SDK github repository for instances of the iOS issue:
https://github.com/stripe/stripe-terminal-ios/issues

For the android issue:
This error value looks like an Android error:
com.stripe.stripeterminal.external.models.TerminalException: API_CONNECTION_ERROR (null)
This is likely the same as this documented API error:
https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-terminal-exception/-terminal-error-code/-s-t-r-i-p-e_-a-p-i_-c-o-n-n-e-c-t-i-o-n_-e-r-r-o-r/index.html
As you can see from that error, it happens when the internet connection is bad ("Failure to connect to Stripe's API"), not because of any behavior on the Stripe backend.

**Comment by maggiewhite-stripe** [comment]
Your report says "I needed to test the TTP (backend update)" - what are you updating here? There is no concept of an update for the Tap to Pay on Android reader.

Can you provide more information about the exact causes of the issue on Tap to Pay on Android? Some helpful information would be:
- An example payment intent ID when this issue occurred
- Instructions to reproduce the issue
- A clear description of the observed behavior on Tap to Pay on Android

If this issue was observed with mobile wallets, there was an improvement to Tap to Pay on Android where mobile wallets took a long time or multiple taps to collect a payment that shipped with version 2.21.0.

**Comment by xez4** [comment]
it looks like you're right about internet connection, let's close this issue
