### ISSUE TITLE
Compatibility issue with Square Reader SDK

### ISSUE THREAD

**Issue by ssavic** [stripe/stripe-terminal-android#351]
Compatibility issue when app has both Square Reader SDK and Stripe Terminal SDK.  Looks like a pervious issue that was fixed in 2.17 was reintroduced in 2.19 and still present in latest 2.22.

## Summary
https://github.com/stripe/stripe-terminal-android/issues/283#issuecomment-1359709040

## Android version
13.0

## Impacted devices (Android devices or readers)
Google Pixel 6A

## SDK version
2.22

## Other information
<img width="1810" alt="Screen Shot 2023-07-12 at 12 03 07 PM" src="https://github.com/stripe/stripe-terminal-android/assets/1315382/2e5eb7bd-3080-4328-912f-13f5daac4cb0">

**Comment by chr-stripe** [comment]
The method it looks like it's trying to invoke has a signature that seems to look like [this one](https://github.com/square/wire/blob/9d0fcfce386cc964fe30521c017af520de59c7df/wire-runtime/src/jvmMain/kotlin/com/squareup/wire/internal/reflection.kt#L79-L90):

```kotlin
fun <M : Message<M, B>, B : Message.Builder<M, B>> createRuntimeMessageAdapter(
  messageType: Class<M>,
  writeIdentityValues: Boolean,
): RuntimeMessageAdapter<M, B>
```

This method signature only seems to exist up until version `4.5.1` of Wire, though. In `4.5.2`, it was changed in [04afa9f88e](https://github.com/square/wire/commit/04afa9f88e#diff-0013d260c68ccd1defa2655b1b5296437926cf26d21889a3a7596b7f7ed7cbc0R87-R100) to this:

```kotlin
fun <M : Message<M, B>, B : Message.Builder<M, B>> createRuntimeMessageAdapter(
  messageType: Class<M>,
  writeIdentityValues: Boolean,
  loader: ClassLoader,
): RuntimeMessageAdapter<M, B>
```

Stripe Terminal SDK `2.22.0` is using version `4.7.2` of Wire, which is currently the latest available version. I suspect that the Square Reader SDK is being compiled against an older version with the older method signature, and thus crashes at runtime because the newer version from the Stripe Terminal SDK is what's actually ending up in your compiled application (Gradle has to pick one version or the other, so by default it chooses the highest version being requested), so the method it's trying to invoke no longer exists due to the additional parameter that was added.

I think you will need to file a ticket against the Square Reader SDK project and request for them to ship an update that uses a more modern version of Wire. This looks effectively like the same kind of issue [I previously described in](https://github.com/stripe/stripe-terminal-android/issues/278#issuecomment-1344584355) #278, but in that ticket I believe Square was using the more recent version of Wire than Stripe was; here it seems like the opposite case.

**Comment by TatsuUkraine** [comment]
had this issue before. try to add this to your app/build.gradle file
```
dependencies {
  ......
  implementation 'com.squareup.wire:wire-gson-support:4.5.2'
}
```

**Comment by TatsuUkraine** [comment]
@chr-stripe just a side note, 2.22.0 is incompatible with Stripe SDK and I can assume with Square Reader SDK as well (since it also uses the same bcprov-jdk deps) https://github.com/stripe/stripe-terminal-android/issues/349

**Comment by TatsuUkraine** [comment]
> @ssavic I had this issue before. try to add this to your app/build.gradle file
> 
> ```
> dependencies {
>   ......
>   implementation 'com.squareup.wire:wire-gson-support:4.5.2'
> }
> ```

Square Reader SDK still using 4.4.0 I think. This will force all your deps using 4.5.2 (I think this one is used by Stripe Terminal SDK currently). But overall I agree, it's a question to the Square team to fix this

**Comment by ssavic** [comment]
Thank you both.  I will reach out to Square team.

@TatsuUkraine your solution does work for me. On a side note I do have Stripe-Android SDK installed alongside Terminal, Stripe version is 20.8.0 and mine is working fine without any crashes.

**Comment by TatsuUkraine** [comment]
It's probably localmobile deps then 🤔
