### ISSUE TITLE
BPos Messaging Changes To Fast

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#39]
When we use this reader and deliberately put the card in the wrong way, swipe an EMV card (essentially to force the reader to tell the user to choose a different method) we get the following messages returned after one action..

**This is when swiping a card that should be TAP or insert.**
2019-05-23 17:17:16.120 7101-7101/? D/Log: class=BbposDeviceControllerListener message=onRequestDisplayText(INSERT_CARD)
2019-05-23 17:17:16.166 7101-7101/? D/Log: class=BbposDeviceControllerListener message=onRequestDisplayText(INSERT_SWIPE_OR_TRY_ANOTHER_CARD)
2019-05-23 17:17:16.201 7101-7101/? D/Log: class=BbposDeviceControllerListener message=onRequestDisplayText(PRESENT_CARD)
2019-05-23 17:17:16.237 7101-7101/? D/Log: class=BbposDeviceControllerListener message=onWaitingForCard(SWIPE_OR_INSERT_OR_TAP)
s

Realistically the messaging should be "Insert Card" and then hold there until operator tries again. 

I've attached a video of what this looks like when outputing the messaging direct to screen.
https://drive.google.com/file/d/1sILPbTWGSUWYus_1zmH0YSh9CRdyx1Jw/view?usp=sharing

**Comment by danwaters-stripe** [comment]
Yeah, I definitely see the issue. I believe the logs you include will translate to two calls to your `ReaderDisplayListener`. First to `onRequestReaderDisplayMessage(INSERT_CARD)` then to `onRequestReaderInput(Swipe/Insert/Tap)`. 

So I think the issue is that you're displaying both of them in the same area, when they're actually conveying slightly different information. Basically, `onRequestReaderInput` will convey all types of cards that the reader is currently ready to accept, while `onRequestReaderDisplayMessage` will try to convey the most immediately relevant message to the user. 

In this case, it's notifying you that the reader is currently able to accept swipe, insert, or tap, but because you're trying to swipe an EMV card, it's telling the user that they should try inserting it instead. I'd probably recommend showing `ReaderDisplayMessages` to users immediately, while keeping `onRequestReaderInput` as internal state or as a static message somewhere else on the screen.

Does that make sense? We're definitely down to hear feedback on this if it doesn't work for you.

**Comment by chander-stripe** [comment]
Closing stale issue - @legomanaustralia please let us know if you're continuing to see this issue on the latest RC1 release. Thanks!
