### ISSUE TITLE
LOCAL_MOBILE_UNSUPPORTED_DEVICE

### ISSUE THREAD

**Issue by avoloshinn** [stripe/stripe-terminal-android#392]
## Summary

I'm implementing Tap to Pay, when I try to use discoverReaders() I get the error LOCAL_MOBILE_UNSUPPORTED_DEVICE.
When using localmobile:2.18.0 everything works, starting from the next versions it doesn’t. TEE is present on the device, Google protection is working, unroot. I don't understand the reason.

## Android version
Android 11

## SDK version
3.1.0

**Comment by avoloshinn** [comment]
![изображение](https://github.com/stripe/stripe-terminal-android/assets/27087093/4ec36c30-8198-4b2e-86e0-182a822a8fd3)

**Comment by maggiewhite-stripe** [comment]
@avoloshinn Thanks for your bug report. It's confusing that your device works with SDK version 2.18 because SDK versions below 2.20.0 have been deprecated, and connecting to the Tap to Pay on Android reader fails on those versions.

Can you share more details about the type of device (model and manufacturer) and some information that would help us find the logs for your device? The Android logcat logs would be helpful. If that's not possible, the account ID or application name and approximate time, date, and timezone would help us locate the logs on our side.

**Comment by jolen10** [comment]
I would like to second this motion.

As mentioned by the OP, we are now getting an error discovering tap to pay (when running on debug, e.g. on Android Studio). The error message says "Debuggable applications are not supported in the production version of the localmobile reader. Please use a simulated version of the reader by setting `DiscoveryConfiguration.isSimulated` to true."

The idea is to test tap to pay using Stripe's physical test cards but setting the `DiscoveryConfiguration.isSimulated` to true will just use a simulated card.

This issue did actually start before version 3.x.x but we ignored it as it was working with a previous version and just decided not to use the latest until 3.x.x. I'm not sure (as I can't confirm at the moment), the latest version that it worked is 2.20.1.

**Comment by maggiewhite-stripe** [comment]
@jolen10 Thanks for your report. The issue you described is not the same as the one reported by OP - the error messages are different. Please file a separate issue for the error message starting with "Debuggable applications are not supported..." so we can keep the discussion in each github issue focused on one issue at a time.

**Comment by jolen10** [comment]
@maggiewhite-stripe, ohhh... sorry about that, at quick glance I thought it was the same but you're right it's a different one. I'll create a separate one.
