### ISSUE TITLE
Question about HTTP timeout

### ISSUE THREAD

**Issue by tom42530** [stripe/stripe-terminal-android#462]
Hi,

I would like to know what is the default HTTP timeout configured in stripe terminal sdk  for rest call.

For my part with the tests it seems infinite

It is possible to change call timeout by public method?

Thanks in advance

**Comment by bric-stripe** [comment]
Hi, there may be differences depending on SDK version in use and readers being used but I believe the API calls should timeout after 90 seconds at most.

> For my part with the tests it seems infinite

can you expand an how you were testing? The requests should always timeout. `collectPaymentMethod` has a very long timeout but its not due to network requests. It's waiting for the customer to present the card on the reader so its intentionally very long, but I believe should timeout after 60 minutes.

> It is possible to change call timeout by public method?

no, these are not configurable.

**Comment by tom42530** [comment]
Yes you're right it's 90 second (30 s per call with 3 tries for each requests)
