### ISSUE TITLE
Forward payment intent for offline payment.

### ISSUE THREAD

**Issue by dev-innopix** [stripe/stripe-terminal-android#485]
We integrated stripeterminal sdk for collecting payments in our android project. 

It's work fine for collecting online payments, but for offline payments some time payment intent is not forwarded to stripe or taking longer time or we have to re run app. So how can we solve this issue? Is there any way to  forcefully forward the offline payment when device get internet.

**Comment by dver-stripe** [comment]
Hey there! Sorry to hear you're having trouble. There's currently no way to force stored payments to sync immediately, unfortunately. In order to help us investigate further, would you be able to provide the following:

* what version of the Android SDK you're integrating with
* an example PaymentIntent that took longer than expected to forward

**Comment by dev-innopix** [comment]
We are using 3.8.0 version. There are to many payment intents which are not forwarded.

**Comment by dver-stripe** [comment]
Thanks for the information. I see all these payments were collected with SDK 3.7.0; their forwarding was delayed due to a known issue in 3.7 that has been resolved in 3.8. You shouldn't see further instances of this going forward.
