### ISSUE TITLE
Discovery process restrictions

### ISSUE THREAD

**Issue by ball1008** [stripe/stripe-terminal-android#65]
I have several tablets running in my customer environments.  I want to show a list of readers that are available for connection.  If a reader is already connected to another tablet, I want to show it in a connected status.  If a reader is not yet connected, I want to provide a connect button so the user can connect the desired reader.  When I run discovery and a reader is connected, I get an error saying  "You must disconnect from reader before discovering readers.".  Is there a way to do what I have described?

**Comment by danwaters-stripe** [comment]
I think this flow won't work exactly as described, since readers that are currently connected to a device won't show up when you call `discoverReaders`. However, outside of that, it shouldn't be a problem. Also, you will have to disconnect from a reader before calling `discoverReaders`. If you don't, you'll run into the "You must disconnect from reader before discovering readers" error.

**Comment by ball1008** [comment]
Dan,

Once connected, we have a button to disconnect the reader.  It is working.  We
seem to be connecting but we never get the success connectreadercallback.  If
we aren't connecting correctly, I would think we wouldn't get the reader info
(battery level, version number).  So if we are connecting, why do we not get
success callback?  Why isn't our reader showing on the dashboard?  It also
seems odd that the discover callback isn't called until we connect to a reader
and not when the list of readers are returned.  We have studied the
documentation, tried multiple iterations of code with no luck.    

Thanks,
Jen
Do-Aye!


On 9/26/2019 at 4:57 PM, danwaters-stripe <notifications@github.com> wrote: 
I think this flow won't work exactly as described, since readers that are
currently connected to a device won't show up when you call discoverReaders.
However, outside of that, it shouldn't be a problem. Also, you will have to
disconnect from a reader before calling discoverReaders. If you don't, you'll
run into the "You must disconnect from reader before discovering readers"
error.

**Comment by danwaters-stripe** [comment]
Yeah, this flow can be a little confusing. A couple clarifications to help explain:

1. There are two parts to the connection process. Step one is to physically connect to the bluetooth device (this is when `onConnectionStatusChange(CONNECTED)` is called). Step two is to register the reader with the Stripe API. This is what's failing in your integration, and the connect reader callback won't be called until the reader is registered. This is also why your reader isn't showing up in the dashboard. For some reason, that API call is never getting to Stripe's backend.
2. `discoverReaders` continues to run and discover new readers until it is either cancelled explicitly, or cancelled implicitly (by calling `connectReader`). This is why the discover callback isn't called until you call `connectReader`.

Hope that helps! The core issue we need to figure out is why you haven't been able to register the reader with the Stripe API. We've never seen a registration request from your account ID, which is why I think it might be a network issue. Have you tried connecting to a reader with our example app? I think that will help shed some light on the issue.

**Comment by danwaters-stripe** [comment]
Hi @ball1008 , have you managed to make any headway on this issue? I'd love to figure out why you haven't been able to register your readers with the Stripe API.

**Comment by ball1008** [comment]
Unfortunately, we have not been able to get past this issue.

**Comment by chander-stripe** [comment]
Closing out this stale issue. If you suspect a bug with the SDK, please don't hesitate to file a new issue. If you need further debugging help, please reach out to the Stripe technical support team. Thanks!

**Comment by vivekvardhanadepu** [comment]
@danwaters-stripe What is the motive behind restricting discovering readers after connecting to a reader?

**Comment by billfinn-stripe** [comment]
Hi @vivekvardhanadepu -- we currently enforce a discover -> connect -> disconnect lifecycle for readers. It's easy to reason about, and we currently don't know of any use cases that require a deviation from this paradigm.

To help us understand your context, what use case are you trying to meet where you want to discover readers while still being connected to a reader?

**Comment by vivekvardhanadepu** [comment]
@billfinn-stripe what if I want to look for readers when I am already connected to a reader. I will connect to the new ones if available.
Right now, we need to disconnect before discovering new readers. So, if the new readers are not found, then we have to connect to the old reader again which is resulting in calling redundant disconnect+connect

**Comment by ball1008** [comment]
The latest release seems to have resolved the callback issues we were encountering.  We are connecting and disconnecting without issue.

**Comment by billfinn-stripe** [comment]
> what if I want to look for readers when I am already connected to a reader. I will connect to the new ones if available. Right now, we need to disconnect before discovering new readers. So, if the new readers are not found, then we have to connect to the old reader again which is resulting in calling redundant disconnect+connect

Can you say a little bit more about what's happening with the POS device and the reader in this case? Under what circumstances and how often does it happen where the user wants to connect to a new reader, but it's not found?

**Comment by vivekvardhanadepu** [comment]
> > what if I want to look for readers when I am already connected to a reader. I will connect to the new ones if available. Right now, we need to disconnect before discovering new readers. So, if the new readers are not found, then we have to connect to the old reader again which is resulting in calling redundant disconnect+connect
> 
> Can you say a little bit more about what's happening with the POS device and the reader in this case? Under what circumstances and how often does it happen where the user wants to connect to a new reader, but it's not found?

Not often, but, it might happen right? I thought it would be better to be able to discover readers while being connected just like how normal bluetooth device connection flow works in mobile phones
